(global-linum-mode t)
(tool-bar-mode nil)
(menu-bar-mode nil)
(scroll-bar-mode nil)
(setq make-backup-files nil)
(setq require-final-newline t)
(setq icomplete-mode t)
(show-paren-mode t)
(setq x-select-enable-clipboard t)
