(require 'ido)
(ido-mode t)
(setq ido-enable-flex-matching t) ;; fuzzy finding no ido
(global-linum-mode t)
(tool-bar-mode nil)
(menu-bar-mode nil)
(scroll-bar-mode nil)
(setq make-backup-files nil)
(setq require-final-newline t)
(setq icomplete-mode t)
(show-paren-mode t)
(setq x-select-enable-clipboard t)
(setq split-width-threshold nil)
(setq inhibit-startup-screen t)
(add-hook 'before-save-hook 'delete-trailing-whitespace)

(custom-set-faces 
 '(default ((t (:foreground "ivory" :background "black"))))
 '(cursor ((t (:background "lavender" :foreground "black"))))
 '(show-paren-match ((t (:background "dark cyan"))))
 '(isearch ((t (:background "light green" :foreground "black"))))
 '(linum ((t (:foreground "LightBlue3"))))
 '(font-lock-constant-face ((t (:foreground "MistyRose3"))))
 '(font-lock-string-face ((t (:foreground "LightBlue3"))))
 '(font-lock-builtin-face ((t (:foreground "Goldenrod"))))
 ;'(font-lock-builtin-face ((t (:foreground "ivory"))))
 '(font-lock-keyword-face ((t (:foreground "khaki1"))))
 '(font-lock-preprocessor-face ((t (:foreground "ffa0a0"))))
 '(font-lock-comment-face ((t (:foreground "#62c600"))))
 '(font-lock-type-face ((t (:foreground "navajo white"))))
 '(font-lock-function-name-face ((t (:foreground "LightBlue4" :weight bold))))
)
